### ISSUE TITLE
Headless scraping?

### ISSUE THREAD

**Issue by scrouthtv** [graysky2/kodi-standalone-service#10]
_Not really an issue with this software but rather a question_

If I use this to run Kodi without the GUI, what would be the easiest way of initiating the scraping process?
I've read about either using a MySQL Setup and somehow making the dbs on my own (?) although I can't find a cli scraper and something with kodi-send.

Does anyone have experience regarding this?
Thanks for the help

**Comment by graysky2** [comment]
You are confused about these services... they are not headless.  You should probably post your question to the [kodi forum](https://forum.kodi.tv/)as you will get very limited exposure on this issue tracker.  You can use an external database and you can use kodi-send or [texture-cache](https://github.com/MilhouseVH/texturecache.py) to trigger an update to that (or a local) database.
