### ISSUE TITLE
libcec/ubuntu: Needs membership of dialout group

### ISSUE THREAD

**Issue by daenney** [graysky2/kodi-standalone-service#14]
I'm not quite sure how to handle this, but on Ubuntu the `kodi` user needs to be a member of the `dialout` group in order to be able to access `/dev/ttyXXXX` devices.

This happens b/c of the following udev rule in Ubuntu (I would imagine Debian has the same):

```
rules.d/50-udev-default.rules:25:KERNEL=="tty[A-Z]*[0-9]|ttymxc[0-9]*|pppox[0-9]*|ircomm[0-9]*|noz[0-9]*|rfcomm[0-9]*", GROUP="dialout"
```

This could be fixed by adding a `m kodi dialout` but it'll result in the creation of the `dialout` group on other systems like Arch.

**Comment by graysky2** [comment]
I think it sounds like a packaging issue... I don't want to pollute other distros with Ubuntu-specific stuff.

**Comment by graysky2** [comment]
Thanks for reporting, see the above commit.
