### ISSUE TITLE
kodi user needs to be in sudo group on Raspbian

### ISSUE THREAD

**Issue by heini** [graysky2/kodi-standalone-service#16]
To be able to install the Widevine CDM on Raspbian (arm), the kodi user needs to be able to execute some commands as root, and therefor needs to be a member of the sudo group (or have a special sudoers file).

**Comment by graysky2** [comment]
> Users of Arch ARM should NOT use this method as the distro package provides analogous functionality.

This service is intended to run on x86_64 only.  I do not know about Raspbian, but Arch ARM's kodi package ships with its own service and related files.  I do not recommend using this on any ARM distro.
