### ISSUE TITLE
Why there is mysqld.service in the After option?

### ISSUE THREAD

**Issue by jonnsl** [graysky2/kodi-standalone-service#2]
I don't share the library of my kodi installation, but I happen to have mariadb installed (for zoneminder), having 'mysqld.service' in the 'After' option of the kodi unit file makes the initialization of kodi be delayed until mariadb finish loading, which is completely unnecessary in my case, but may be required if the library sharing feature of kodi is being used.
How can we satisfy both use cases?
1 - not delaying the start of kodi if the library sharing feature is not being used, or the mysql that has the library is not on this machine, but mysql happens to be installed;
2 - start kodi after mysql, if the library sharing feature is being used AND the library is in a database in the same machine as kodi.

**Comment by graysky2** [comment]
...but how can systemd know if the user has kodi configured to use a mysql db or the local ones?
