### ISSUE TITLE
AUR package is gone?

### ISSUE THREAD

**Issue by desbma** [graysky2/kodi-standalone-service#22]
https://aur.archlinux.org/packages/kodi-standalone-service/

**Comment by graysky2** [comment]
It's there... but the name change of https://github.com/graysky2/kodi-standalone-service/commit/11cbb1caedd72e84969e83f219fdebd3b5ec5261 makes it not come up.  I [asked](https://bbs.archlinux.org/viewtopic.php?pid=1931057) in the forums and will adjust.  For now, just search for [any](https://aur.archlinux.org/packages/kodi-standalone-gbm-service/) of the 3 names.

**Comment by desbma** [comment]
I see...

Worth noting: AUR helpers like Yay also warn that the package is not in the AUR.

**Comment by graysky2** [comment]
It's not a split-package anymore so it comes up just fine in a search.
