### ISSUE TITLE
Server is already active for display 0 when staring kodi-x11

### ISSUE THREAD

**Issue by dflock** [graysky2/kodi-standalone-service#28]
Trying to get this working on Ubuntu, so that I can run Kodi as a headless server on the desktop and use a Chromebook to watch stuff from it, using the web interface. This works if I manually start Kodi on the desktop and put the window out of the way somewhere, but I'd rather it was running as a service.

This is what I'm running on the desktop:

```
$ neofetch --backend off
--------------------- 
OS: Ubuntu 20.04.1 LTS x86_64 
Kernel: 5.4.0-52-generic 
Shell: bash 5.0.17 
Resolution: 1920x1080, 1920x1080, 1920x1080 
DE: Xfce 
WM: Xfwm4 
WM Theme: Arc-Dark 
Theme: Arc-Dark [GTK2/3] 
Icons: Papirus-Dark [GTK2/3] 
Terminal: kitty 
CPU: Intel i7-6700K (8) @ 4.200GHz 
GPU: Intel HD Graphics 530 
Memory: 21669MiB / 64206MiB 
```

To install kodi-standalone, I did this:

```shell
$ sudo mkdir /usr/lib/systemd/system
$ sudo cp init/*.service /usr/lib/systemd/system/
$ sudo cp init/sysusers.conf /usr/lib/sysusers.d/
$ sudo nano /usr/lib/sysusers.d/sysusers.conf

$ sudo systemd-sysusers
Creating group kodi with gid 996.
Creating group optical with gid 995.
Creating user kodi (Kodi User) with uid 996 and gid 996.

$ sudo cp init/tmpfiles.conf /usr/lib/tmpfiles.d/
$ sudo systemd-tmpfiles --create

$ sudo cp polkit/10-kodi.rules /usr/share/polkit-1/rules.d/
$ sudo udevadm control --reload-rules && sudo udevadm trigger
```

Then I tried to start it:

```
$ sudo systemctl start kodi-x11.service 
$ systemctl status kodi-x11.service 

● kodi-x11.service - Kodi standalone (X11)
     Loaded: loaded (/usr/lib/systemd/system/kodi-x11.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2020-12-18 15:28:44 PST; 8s ago
    Process: 577130 ExecStart=/usr/bin/xinit /usr/bin/kodi-standalone -- :0 -quiet -nolisten tcp vt1 (code=killed, sig>
    Process: 577136 ExecStop=/usr/bin/killall --user kodi --exact --wait kodi-x11 (code=exited, status=1/FAILURE)
   Main PID: 577130 (code=killed, signal=HUP)

Dec 18 15:28:44 duncan-desktop systemd[1]: Started Kodi standalone (X11).
Dec 18 15:28:44 duncan-desktop killall[577136]: kodi-x11: no process found
Dec 18 15:28:44 duncan-desktop systemd[1]: kodi-x11.service: Control process exited, code=exited, status=1/FAILURE
Dec 18 15:28:44 duncan-desktop systemd[1]: kodi-x11.service: Failed with result 'exit-code'.
```

So, then... I tried it again...

```
$ sudo systemctl start kodi-x11.service
$ systemctl status kodi-x11.service 

● kodi-x11.service - Kodi standalone (X11)
     Loaded: loaded (/usr/lib/systemd/system/kodi-x11.service; disabled; vendor preset: enabled)
     Active: active (running) since Fri 2020-12-18 15:29:14 PST; 4s ago
   Main PID: 577220 (xinit)
      Tasks: 2 (limit: 76980)
     Memory: 1.9M
     CGroup: /system.slice/kodi-x11.service
             └─577220 /usr/bin/xinit /usr/bin/kodi-standalone -- :0 -quiet -nolisten tcp vt1

Dec 18 15:29:14 duncan-desktop xinit[577248]: Fatal server error:
Dec 18 15:29:14 duncan-desktop xinit[577248]: (EE) Server is already active for display 0
Dec 18 15:29:14 duncan-desktop xinit[577248]:         If this server is no longer running, remove /tmp/.X0-lock
Dec 18 15:29:14 duncan-desktop xinit[577248]:         and start again.
Dec 18 15:29:14 duncan-desktop xinit[577248]: (EE)
Dec 18 15:29:14 duncan-desktop xinit[577248]: (EE)
Dec 18 15:29:14 duncan-desktop xinit[577248]: Please consult the The X.Org Foundation support
Dec 18 15:29:14 duncan-desktop xinit[577248]:          at http://wiki.x.org
Dec 18 15:29:14 duncan-desktop xinit[577248]:  for help.
Dec 18 15:29:14 duncan-desktop xinit[577248]: (EE)

$ systemctl status kodi-x11.service 

● kodi-x11.service - Kodi standalone (X11)
     Loaded: loaded (/usr/lib/systemd/system/kodi-x11.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2020-12-18 15:33:42 PST; 6min ago
    Process: 577817 ExecStart=/usr/bin/xinit /usr/bin/kodi-standalone -- :0 -quiet -nolisten tcp vt1 (code=exited, status=1/FAILURE)
   Main PID: 577817 (code=exited, status=1/FAILURE)

Dec 18 15:33:27 duncan-desktop xinit[577827]: Please consult the The X.Org Foundation support
Dec 18 15:33:27 duncan-desktop xinit[577827]:          at http://wiki.x.org
Dec 18 15:33:27 duncan-desktop xinit[577827]:  for help.
Dec 18 15:33:27 duncan-desktop xinit[577827]: (EE)
Dec 18 15:33:42 duncan-desktop xinit[577817]: No protocol specified
Dec 18 15:33:42 duncan-desktop xinit[577817]: /usr/bin/xinit: giving up
Dec 18 15:33:42 duncan-desktop xinit[577817]: /usr/bin/xinit: unable to connect to X server: Resource temporarily unavailable
Dec 18 15:33:42 duncan-desktop xinit[577817]: /usr/bin/xinit: server error
Dec 18 15:33:42 duncan-desktop systemd[1]: kodi-x11.service: Main process exited, code=exited, status=1/FAILURE
Dec 18 15:33:42 duncan-desktop systemd[1]: kodi-x11.service: Failed with result 'exit-code'.
```

Not sure if relevant, but I only have one xorg process running:

```
$ pgrep -af xorg
1543 /usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
```

Not sure where to go from here?

**Comment by graysky2** [comment]
Not sure why you're getting the no protocol specified nor the resource unavailable error.  I am not expert with Ubuntu and how things are packaged.  I am assuming you have the needed dependencies.  Are you missing any driver for your hardware?  I also don't know if there are differences in how xorg is packaged/configured Ubuntu vs Arch.

Can you try the more simplistic kodi-gbm?

**Comment by dflock** [comment]
> Can you try the more simplistic kodi-gbm?

I tried that and it killed my X session/server/everything, had to reboot :man_shrugging:

**Comment by graysky2** [comment]
Are you trying to run kodi-gbm or kodi-x11 while you have an existing graphical session?  If so, that will not work.

**Comment by dflock** [comment]
Yes.

I'm trying to get this working on Ubuntu, so that I can run Kodi as a headless server on the desktop and use a Chromebook to watch stuff from it, using the web interface.

This works if I manually start Kodi on the desktop and put the window out of the way somewhere, but I'd rather it was running as a headless service.

When I run just run kodi manually, it'll run kodi-x11 and open in a window, so that works fine. I just don't really want the window - I want it to be headless. Is there a way to run Kodi to xvfb or something?

**Comment by graysky2** [comment]
> so that I can run Kodi as a headless server on the desktop and use a Chromebook to watch stuff from it, using the web interface

I don't think the web interface allows you to watch anything.  I think it is just a remote control to the physical display.

>When I run just run kodi manually, it'll run kodi-x11 and open in a window, so that works fine. I just don't really want the window - I want it to be headless. Is there a way to run Kodi to xvfb or something?

My services here will not give you a headless kodi.  They are meant to allow a box to run kodi as the only GUI application.  If your goal is to have a kodi server with a shared database, you might find a docker image useful.  I believe they can run headless for this purpose.  If you don't care about a shared database, I don't see an advantage to going through the trouble.  Just serve up content via NFS and be done with it.

**Comment by dflock** [comment]
> I don't think the web interface allows you to watch anything. I think it is just a remote control to the physical display.

No, it can stream content to a web browser too, which is what I want. Maybe I should just use a different media server that just does that and nothing else.

**Comment by graysky2** [comment]
Whether or not it streams isn't the issue.  If you want headless kodi, seek out a docker image.  https://hub.docker.com/search/?q=kodi&type=image
