### ISSUE TITLE
Run kodi additionally to the display-manager

### ISSUE THREAD

**Issue by staeglis** [graysky2/kodi-standalone-service#29]
Hi,

I've tried without success to run kodi-standalone-service additionally to the displaymanager. The idea is that it should be always possible to get a full desktop.

Do you have an idea how to achive this? I've changed the install section in the unit file to WantedBy=multi-user.target

Best,
Stefan

**Comment by graysky2** [comment]
That is not possible.  These service units are for a standalone use case.  They are not intended to run alongside a display manger.  If you want this ability, run one of these on the primary display and run something like [tigervnc in a headless configuration](https://wiki.archlinux.org/index.php/TigerVNC#Running_vncserver_for_virtual_(headless)_sessions) for your use to remote into for X applications.
