### ISSUE TITLE
Creating user fails

### ISSUE THREAD

**Issue by lucasvc** [graysky2/kodi-standalone-service#3]
The [`README` section for Other distros](https://github.com/graysky2/kodi-standalone-service#other-distros) is not correct, as the `useradd` commnads lacks of the login name (and no shell options,...).
The best doc is to do the same [from `readme.install#post_install` in the AUR original package](https://aur.archlinux.org/cgit/aur.git/tree/readme.install?h=kodi-standalone-service#n1).

**Comment by graysky2** [comment]
Thanks, fixed 3d75368
