### ISSUE TITLE
GBM service doesn't work with Kodi 19 beta

### ISSUE THREAD

**Issue by a-andre** [graysky2/kodi-standalone-service#33]
The windowing option has been removed from wrapper script. See https://github.com/xbmc/xbmc/commit/e8002707f65cbb9d59004718641a0f9053dd098f.

It seems `/usr/bin/kodi-standalone` has to be replaced in service files.

**Comment by graysky2** [comment]
Thanks for reporting.  Please try the latest version and report back.
