### ISSUE TITLE
kodi-wayland encrypted h.264 video streams show as flickering screens dominated by a primary color.

### ISSUE THREAD

**Issue by david-morris** [graysky2/kodi-standalone-service#35]
I really don't know what project this issue should be filed against, but if I want to use Netflix or Amazon VOD, I need to use the X11 service rather than Wayland.

The videos I noticed this with were Netfix videos, which showed as green screens with moving static that flashed cyan, and Amazon VOD videos, which showed as magenta screens with moving static. German television is geoblocked instead of encrypted, and that played fine with an H.264 stream.

The audio was fine. The X11 standalone Kodi plays the Netflix and Amazon VOD videos fine, so that's an acceptable workaround I'll be using for the foreseeable future.

`kodi.log` with debug logging enabled only reported the stream buffering events, it didn't complain about the video stream.

Let me know if there's something I can do to get this issue to the right project.

**Comment by graysky2** [comment]
Firstly, what distro are you using and what kodi version?

Second thought is an acknowledgment that I don't know if this is a function of something not getting setup with respect to my service files here or something relating to your wayland setup, or to kodi-wayland.

First thing to do would be to verify that you can run `kodi-wayland` without the standalone service, ie as your user with some DE you installed.  If you see the issues there, I would think it's not the service but something not setup properly on your side or some wayland bug or kodi-wayland bug.

If it does play fine there, but not when you launch with `kodi-wayland.service`, then we need to figure out what is wrong and adjust accordingly.

Can you remove the standalone package and try as I describe?

**Comment by david-morris** [comment]
Hi graysky,
I am running kodi-wayland on Arch.  It's a server install, so I actually had to install an x server to run kodi-x11.  I do suspect this has more to do with the Wayland stack than your package, but I just don't have the expertise to figure out which project has the issue.  Do you have any suggestions?

As far as pinpointing whether the issue is specific to the cage, I don't have a DE, and weston won't start on my machine.

**Comment by graysky2** [comment]
I can't really do much without knowing if it's my stuff causing the issue.

> First thing to do would be to verify that you can run kodi-wayland without the standalone service, ie as your user with some DE you installed. If you see the issues there, I would think it's not the service but something not setup properly on your side or some wayland bug or kodi-wayland bug.

**Comment by david-morris** [comment]
Ok, I can't think of where this issue should be moved to.  Hopefully if anyone else has this issue, my workaround helps them too.

Thanks for the systemd services! It's pretty slick to be able to start kodi on boot so easily.
