### ISSUE TITLE
/etc/conf.d/kodi-standalone overwrites existing config

### ISSUE THREAD

**Issue by ghen2** [graysky2/kodi-standalone-service#36]
I just found out that since commit https://github.com/graysky2/kodi-standalone-service/commit/546b6863a4392c98cc34dec8ded0e19be25006fb, the installed example config file overwrites any existing config file. :-(  It is not properly registered as a `backup` configfile in pacman (which would create a .pacnew version instead).

Please add backup=('etc/conf.d/kodi-standalone') to the PKGBUILD.

**Comment by graysky2** [comment]
Fixed in 1.132-3 ... not really an upstream issue, more of an AUR packing issue but whatever :p
