### ISSUE TITLE
Does not work on raspi os

### ISSUE THREAD

**Issue by solsticedhiver** [graysky2/kodi-standalone-service#37]
I am trying to make it work on an install  of raspi OS lite.

But the service is not run at start. It is enabled but the log seems to imply it is not even started. May be a condition is not met ?

More oever, when I start to run it manually (from ssh) with `systemctl start kodi-gbm`, I got a prompt on tty1 from sudo like `[sudo] password for kodi`.
I am confused as to why a password is needed and sudo at all ? especially that kodi user has no password.

I am new to raspi OS. It was just working fine on archlinux ARM. :-(

**Comment by graysky2** [comment]
Not sure about RPiOS.  These files are only tested on Arch Linux and Arch ARM.  On Arch ARM: https://github.com/archlinuxarm/PKGBUILDs/blob/master/alarm/kodi-rpi/PKGBUILD#L210-L217

**Comment by solsticedhiver** [comment]
So I added kodi to the sudo group (with NOPASSWD :-() and to render and dialout group
Then I noticed **the polkit rules were not installed by the Makefile, so I added them manually,** and ...

It is still not started at boot. And manually (with `systemctl start kodi-gbm`), the console flashed (three times) like the number of times kodi is started i guess
So wrong permission or something like that

I think this could be closed if this is archlinux only then

**Comment by solsticedhiver** [comment]
There is something weird like `sudo openvt -sw -- su -c ${KODI_BINARY} $SAVED_ARGS` in `/usr/bin/kodi`; That's why it needs sudo right.
If I change it to `${KODI_BINARY} $SAVED_ARGS &`, it works when lauching manually. Still not working at boot though.

Never mind, I found a simple kodi.service that just launch kodi-standalone as main user. But I still need the changes I made in /usr/bin/kodi for that to work too....

**Comment by graysky2** [comment]
> So I added kodi to the sudo group (with NOPASSWD

That is a really REALLY bad idea and totally unnecessary.

> There is something weird like sudo openvt -sw -- su -c ${KODI_BINARY} $SAVED_ARGS in /usr/bin/kodi

To be clear, this is the RPiOS version of kodi which I believe ships with a modified version of that file, see [this](https://forum.kodi.tv/showthread.php?tid=365682&pid=3072985#pid3072985) and https://github.com/popcornmix/xbmc/commits/gbm_matrix/tools/Linux/kodi.sh.in

They could have a totally different method of starting kodi that is not a systemd unit.  I do not know.

For Arch ARM, I revert the changes made to that file when we build.  See: https://github.com/graysky2/xbmc/commit/9c157312057958e0ea68121b33d1713e1d12de2c

**Comment by popcornmix** [comment]
On RPiOS, the openvt method of starting kodi is required for launching kodi from a running X desktop (e.g. from desktop start menu).
X is a DRM master, and it needs to relinquish this in order for kodi to launch. openvt (or chvt) is a method of achieving this. It unfortunately requires sudo, but the pi user (on RPiOS) is already in the sudo group.

I did try starting kodi from systemd and it seemed to work fine if you use kodi-standalone, and set the boot preference to boot to console (so the chvt step isn't required).

You can alternatively add @kodi to `/etc/xdg/lxsession/LXDE-pi/autostart`, and have boot to desktop, and it will be launched after desktop is started.

**Comment by graysky2** [comment]
@popcornmix - Thanks for the explanation.
@solsticedhiver - Can you post your modified working `/usr/bin/kodi` so it can be shared with others?

**Comment by solsticedhiver** [comment]
I just used yours. I mean I applied the patch manually.
[kodi.txt](https://github.com/graysky2/kodi-standalone-service/files/7888328/kodi.txt)

**Comment by graysky2** [comment]
Thanks.  And everything is working as expected for you on RPiOS?

**Comment by solsticedhiver** [comment]
I have not made extensive testing so far, because it is a second device, that I will not be using myself.

But yeah, it boots straight into kodi. That was the goal

**Comment by graysky2** [comment]
https://github.com/graysky2/kodi-standalone-service/commit/594aa29e8dc1a02d566c52601021c48e2ff63756

**Comment by graysky2** [comment]
https://github.com/graysky2/kodi-standalone-service/commit/6e0aedb13f48364863e8df13e1a066515b933da4

**Comment by solsticedhiver** [comment]
oh . I forgot, **I had to change the default boot target to graphical** `systemctl set-default graphical.target` (because your .service set it as display manager I think). I had set it up to console or I don't what it was before

[Edit] and it works fine with your kodi.service. No problem there

I am using raspiOS Lite.
