### ISSUE TITLE
Environment files start with "-"

### ISSUE THREAD

**Issue by david-morris** [graysky2/kodi-standalone-service#39]
The EnvironmentFile parameters start with "-".  This means that the environment files weren't getting loaded.  They're empty by default, of course, but I need to explicitly supply my LIBVA driver.

**Comment by graysky2** [comment]
I'm not sure what action you are expecting...?

**Comment by david-morris** [comment]
I have some time, I'll see if I can get around to making a PR on the weekend.

**Comment by graysky2** [comment]
The service files already have the correct syntax AFAIK, as an example see: https://github.com/graysky2/kodi-standalone-service/blob/master/x86/init/kodi-x11.service#L10

**Comment by david-morris** [comment]
Hmm, you're right.  I was wrong about the source of my problem, and it's reoccurred.  I'll open a PR after I fix whatever was wrong, not necessarily against this repo...
