### ISSUE TITLE
Use AmbientCapabilities=CAP_NET_BIND_SERVICE

### ISSUE THREAD

**Issue by KillWolfVlad** [graysky2/kodi-standalone-service#4]
Use `AmbientCapabilities=CAP_NET_BIND_SERVICE` in `kodi.service` to allow `kodi` use port 80 for webserver.

Patch

```diff
diff --git a/init/kodi.service b/init/kodi.service
index a3bbd75..549c4b9 100644
--- a/init/kodi.service
+++ b/init/kodi.service
@@ -12,6 +12,7 @@ TTYPath=/dev/tty1
 ExecStart=/usr/bin/xinit /usr/bin/kodi-standalone -- :0 -nolisten tcp vt1
 Restart=on-abort
 StandardInput=tty
+AmbientCapabilities=CAP_NET_BIND_SERVICE
 
 [Install]
 WantedBy=multi-user.target
````

This should be work only with `systemd` >= 230

**Comment by graysky2** [comment]
What is the use case for this?  Why not just use 8080 or the like?  I can see problems for systems also running a proper http server on port 80.

**Comment by KillWolfVlad** [comment]
`AmbientCapabilities=CAP_NET_BIND_SERVICE` can allow use any port, not only 80

**Comment by graysky2** [comment]
> AmbientCapabilities=CAP_NET_BIND_SERVICE can allow use any port, not only 80

I read the man page and agree with that statement but you didn't answer my original questions:
>What is the use case for this? Why not just use 8080 or the like?

**Comment by KillWolfVlad** [comment]
> What is the use case for this? Why not just use 8080 or the like?

It is not comfortable. I would like just open `kodi` web interface in browser without any ports (as I open `github.com`, but I don't open `github.com:443`).

**Comment by graysky2** [comment]
You can keep your own version of this in `/etc/system/systemd` with this mod but I don't want to merge since the upstream default is 8080 and that requires no modification.

**Comment by KillWolfVlad** [comment]
> You can keep your own version of this in `/etc/system/systemd` with this mod

Better I create [fork](https://github.com/KillWolfVlad/kodi-standalone-improved-AUR)

**Comment by ammgws** [comment]
Maybe you could mention this in the docs instead of making a fork.  (For those who want to use Kodi on a privileged port without using nginx etc.)

**Comment by graysky2** [comment]
@ammgws - https://github.com/graysky2/kodi-standalone-service/commit/bfa43577d6f53a8cdd04d10fbb4c136639cd2685
