### ISSUE TITLE
ubuntu 20.04 file and folder /etc/sysusers.d/kodi-standalone.conf not found

### ISSUE THREAD

**Issue by amidevous** [graysky2/kodi-standalone-service#40]
on ubuntu 20.04 folder /etc/sysusers.d/

not found not exist

file /etc/sysusers.d/kodi-standalone.conf

not found kodi service not start please solve

**Comment by graysky2** [comment]
The [Makefile](https://github.com/graysky2/kodi-standalone-service/blob/master/Makefile#L51) does not install to that directory, it installs to `/usr/lib/sysusers.d/kodi-standalone.conf` and that should work just fine.

**Comment by amidevous** [comment]
ok but if you want it to install you must first create this folder

/usr/lib/sysusers.d/

because on ubuntu by default this folder does not exist

in other words before your line install you must put a line mkdir

your error comes from you put an install

without putting mkdir before normal that its not installed

your mistake it comes from

`INSTALL_DIR = mkdir -p`

and no

`INSTALL_DIR = $(INSTALL) -d`

its an error have used mkdir to create a folder and not install

it's because of this that it's not installing the

install is to copy a folder and not to create it

**Comment by graysky2** [comment]
I'm confused.  The required command should be `install -p -d /usr/lib/sysusers.d` no?  That is what the Makefile is doing now: https://github.com/graysky2/kodi-standalone-service/blob/master/Makefile#L41

Here is an example installed to a directory that does not exist at all:
```
% make DESTDIR=tit install  
install -p -d "tit/usr/lib/udev/rules.d"
install -p -d "tit/usr/lib/systemd/system"
install -p -d "tit/usr/share/man/man1"
install -p -m644 x86/doc/kodi.service.1 "tit/usr/share/man/man1/kodi.service.1"
install -p -d "tit/etc/conf.d"
install -p -d "tit/usr/lib/sysusers.d"
install -p -m644 x86/udev/99-kodi.rules "tit/usr/lib/udev/rules.d/99-kodi.rules"
install -p -d "tit/usr/lib/tmpfiles.d"
install -p -m644 common/kodi-standalone "tit/etc/conf.d/kodi-standalone"
install -p -m644 x86/init/kodi-gbm.service "tit/usr/lib/systemd/system/kodi-gbm.service"
install -p -m644 x86/init/kodi-wayland.service "tit/usr/lib/systemd/system/kodi-wayland.service"
install -p -m644 x86/init/kodi-x11.service "tit/usr/lib/systemd/system/kodi-x11.service"
install -p -m644 x86/init/tmpfiles.conf "tit/usr/lib/tmpfiles.d/kodi-standalone.conf"
install -p -m644 x86/init/sysusers.conf "tit/usr/lib/sysusers.d/kodi-standalone.conf"

% tree tit
[  80]  tit
├── [  60]  etc
│   └── [  60]  conf.d
│       └── [  60]  kodi-standalone
└── [  80]  usr
    ├── [ 120]  lib
    │   ├── [  60]  systemd
    │   │   └── [ 100]  system
    │   │       ├── [ 641]  kodi-gbm.service
    │   │       ├── [ 696]  kodi-wayland.service
    │   │       └── [ 661]  kodi-x11.service
    │   ├── [  60]  sysusers.d
    │   │   └── [ 723]  kodi-standalone.conf
    │   ├── [  60]  tmpfiles.d
    │   │   └── [ 108]  kodi-standalone.conf
    │   └── [  60]  udev
    │       └── [  60]  rules.d
    │           └── [ 136]  99-kodi.rules
    └── [  60]  share
        └── [  60]  man
            └── [  60]  man1
                └── [2.5K]  kodi.service.1

13 directories, 8 files
```

**Comment by graysky2** [comment]
Closing as I don't think my stuff is wrong as-is. Feel free to reopen if you have evidence otherwise.
