### ISSUE TITLE
[Help] : Kodi service stops displaying after a while of inactivity. 

### ISSUE THREAD

**Issue by fockboi-lgtm** [graysky2/kodi-standalone-service#42]
Hello,

I have been using this service to run Kodi on my Raspberry Pi 4, without a DE.
But unfortunately, I noticed that Kodi goes into sleep with no output. (I use HDMI CEC to control Kodi). I tried to use some of the common solutions on Google, but no luck (most of them are geared to projects having DE/WM) 
Is there something I can do to ensure Kodi doesn't stop the display, or should it be an issue with the OS?

**Comment by graysky2** [comment]
Which distro are you using?  Kodi sleeping would be something in your user's profile.  First recommendation is disable that.

**Comment by fockboi-lgtm** [comment]
I'm using Manjaro ARM edition. Okay, I'll check my profile for sleep mode enabled.

**Comment by graysky2** [comment]
I believe Manjaro ARM uses many of Arch ARM's packages.  If that is the case, you should not manually install anything from here.  The package provides the needed files from here.  I am closing this as your issues are highly unlikely to be related to this stuff but feel free to continue dialog here.
