### ISSUE TITLE
running this on RaspiOS is easier than README suggests

### ISSUE THREAD

**Issue by equinox0815** [graysky2/kodi-standalone-service#44]
I think the [notes](https://github.com/graysky2/kodi-standalone-service#notes-for-users-of-rpios) for RaspiOS users are outdated. To get Kodi running on the latest RaspberryPI OS Lite Images all there is to do is to run these commands as root:
```
apt install kodi libgl1-mesa-dri git
git clone --depth 1 https://github.com/graysky2/kodi-standalone-service
cd kodi-standalone-service
make install
systemd-sysusers
systemd-tmpfiles --create
systemctl enable kodi.service
systemctl set-default graphical.target
reboot
```
I have tested this using a CM4 with both 32bit and 64bit images.

**Comment by graysky2** [comment]
I think the getting the code as you did with git and then calls to systemctl are implied in the [readme](https://github.com/graysky2/kodi-standalone-service#usage) ... not sure about which packages beyond kodi these folks need.

**Comment by equinox0815** [comment]
Yes of course. I only included that for completeness. The things that took me a while to figure out was the minimal list of packages that actually need to be installed to get it working.
Also the line `Set the boot preference to boot to the console` confused me for a while. Especially since it links to a comment that says to switch to `graphical.target` which is IMHO the opposite. If you would use `raspi-config` to accomplish this you need to select `Desktop` not `Console` to switch to the `graphical.target`.
Finally, at least for the current RaspiOS images, it is no longer necessary to replace `/usr/bin/kodi`. I was almost scared off because of this since maintaining such manual changes can be quite cumbersome.

**Comment by graysky2** [comment]
I do not use that distro.  Is the use of `raspi-config` the distro recommended method?

**Comment by equinox0815** [comment]
Yeah i think so. It comes up quite often in tutorials. Also most tools and scripts make use of it. Personally i don't like it too much because i usually deploy stuff using ansible and for idempotence reasons it is much better to do the changes directly rather than calling a script. But i almost always take a look at this script and try to mimic it's behaviour when developing ansible roles.

In this case i looked at [this](https://github.com/RPi-Distro/raspi-config/blob/master/raspi-config#L1385). Switching to the `graphical.target` could be to either done by running `raspi-config` interactively and go to `System Options -> Boot / Auto Login -> Desktop` or by using the non-interactive mode of the tool: 
```
raspi-config nonint do_boot_behaviour B3
```
Essentially this does the same as `systemctl set-default graphical.target`. At least for now.

**Comment by graysky2** [comment]
Do you mind preparing a PR modifying the readme with a minimal set of instructions targeted at RPiOS?  I don't want to cherry pick from this conversation since I do not have experience with that distro.

**Comment by graysky2** [comment]
ping @equinox0815

**Comment by graysky2** [comment]
@equinox0815 plz open a PR

**Comment by jack-mil** [comment]
Hello, I regularily use RpiOS and just successfully installed these services using the information in this issue and the readme. I am happy to document some of the details to help others. I will open a PR and reference this issue soon

**Comment by graysky2** [comment]
Sounds great, thanks.

**Comment by graysky2** [comment]
@jack-mil - Sounds great, thanks.

**Comment by equinox0815** [comment]
@jack-mil Thanks from me as well. Every time i start working on this i get side-tracked. So thanks for taking this off my plate!
