### ISSUE TITLE
breaks under systemd_homed

### ISSUE THREAD

**Issue by Spartan-II-117** [graysky2/kodi-standalone-service#45]
attempted to use this on a new install of Arch today. 
fot the error:  pam_systemd_home(login:account): Not a user managed by systemd-homed: No home for user kodi I attempted to set up kodi as a systemd_homed user to no avail, when i did that it wanted to prompt for authentication 
 pam_systemd_home(login:account): conversation failed 
 pam_systemd_home(login:account): Failed to prompt for password/prompt.

**Comment by graysky2** [comment]
How are you using systemd-homed?  I have never configured it myself.

**Comment by mboleary** [comment]
Hey, so I ran into this today as well and I was able to fix it by editing my `/etc/pam.d/system-auth` file by commenting out the lines that have `pam_systemd_home.so`. I saw where someone did this on [this reddit thread for a related issue](https://www.reddit.com/r/archlinux/comments/ie3cvj/pam_systemd_home_spamming_the_journal_everytime_i/). Also probably worth reading some related documentation:
- https://www.freedesktop.org/software/systemd/man/pam_systemd.html
- https://www.freedesktop.org/software/systemd/man/pam_systemd_home.html

**Comment by Spartan-II-117** [comment]
This was a base arch install, I had not configured ayatemd-homed, or even heard of it before seeing the error messages.

**Comment by graysky2** [comment]
You should not need to comment that out.  I am running the standalone service with pambase's default without issue:
https://github.com/archlinux/svntogit-packages/blob/packages/pambase/trunk/system-auth

EDIT: on a fresh image here, I can actually replicate this yet my `/etc/pam.d/system-auth` is identical to the pkg default and to the other machine.  Must be something else I have installed DE wise.  

```
% status kodi-gbm
○ kodi-gbm.service - Kodi standalone (GBM)
     Loaded: loaded (/usr/lib/systemd/system/kodi-gbm.service; disabled; preset: disabled)
    Drop-In: /etc/systemd/system/kodi-gbm.service.d
             └─override.conf
     Active: inactive (dead)

Jan 23 11:04:51 myth2 systemd[1]: Started Kodi standalone (GBM).
Jan 23 11:04:51 myth2 systemd[889]: pam_systemd_home(login:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Jan 23 11:04:51 myth2 systemd[889]: pam_unix(login:session): session opened for user kodi(uid=989) by LOGIN(uid=0)
Jan 23 11:07:29 myth2 systemd[1]: Stopping Kodi standalone (GBM)...
Jan 23 11:07:29 myth2 systemd[1240]: pam_systemd_home(login:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.
Jan 23 11:07:29 myth2 systemd[1240]: pam_unix(login:session): session opened for user kodi(uid=989) by LOGIN(uid=0)
Jan 23 11:07:32 myth2 systemd[1244]: pam_unix(login:session): session closed for user kodi
Jan 23 11:07:32 myth2 systemd[1]: kodi-gbm.service: Deactivated successfully.
Jan 23 11:07:32 myth2 systemd[1]: Stopped Kodi standalone (GBM).```

**Comment by Spartan-II-117** [comment]
Let me know if there's anything I can do to help troubleshoot

**Comment by graysky2** [comment]
I don't have tons of free time these days.  If the solution lies in some required addition contained in the homed docs, please let me know what you find.  Otherwise, this will have to wait for me to have more free time.

**Comment by graysky2** [comment]
I just realized that I had `systemd-homed` masked.  If I remove that, `kodi-gbm.service` starts as expected.  Do you have your service masked?

**Comment by Spartan-II-117** [comment]
only if it comes masked by default on new installs, how does one mask or un-mask a service?

**Comment by graysky2** [comment]
You have to link the service to `/dev/null` and I do not believe it is masked by default

EDIT: now I cannot reproduce the finding from yesterday.. the status of this service seems unrelated.

**Comment by Spartan-II-117** [comment]
it looks like this was never the problem, the real issue (i think) is that kodi is not properly depending on lzo, and thus fails to start on a fresh install.
