### ISSUE TITLE
Conflict when using `/dev/tty` in Proxmox LXC

### ISSUE THREAD

**Issue by elagil** [graysky2/kodi-standalone-service#47]
Hello,

I use a strange setup, where I use `kodi-standalone` in a Linux container (LXC) on a Proxmox virtual environment (PVE).
My container runs Ubuntu 22.04 without a desktop environment, and I chose the GBM service.

When using the default `TTYPath=/dev/tty1` in `kodi-gbm.service`, there seem to be conflicts with the Proxmox terminal, which apparently also uses tty1.

To be precise, I get notified by bash when launching the terminal:
```
Last login: Sat Dec 30 22:04:28 UTC 2023 on tty1
-bash: cannot set terminal process group (119): Inappropriate ioctl for device
-bash: no job control in this shell
```

When I change that offending line in `kodi-gbm.service` to `TTYPath=/dev/tty2`, that goes away.
I wonder if that is a good way of solving it, as I don't really understand what kodi uses `/dev/ttyX` for.

Probably unrelated, but I see this in the status output of the service:
```
# service kodi-gbm status
* kodi-gbm.service - Kodi standalone (GBM)
     Loaded: loaded (/lib/systemd/system/kodi-gbm.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-12-30 22:09:10 UTC; 3min 42s ago
   Main PID: 137 (kodi-standalone)
      Tasks: 32 (limit: 38159)
     Memory: 277.8M
        CPU: 11.837s
     CGroup: /system.slice/kodi-gbm.service
             |-137 /bin/sh /usr/bin/kodi-standalone
             |-155 "(sd-pam)" "" ""
             |-165 /bin/sh /usr/bin/kodi --standalone
             `-172 /usr/lib/x86_64-linux-gnu/kodi/kodi.bin --standalone

Dec 30 22:09:10 media-player systemd[1]: Started Kodi standalone (GBM).
Dec 30 22:09:10 media-player systemd[137]: pam_unix(login:session): session opened for user kodi(uid=999) by (uid=0)
Dec 30 22:09:10 media-player systemd[137]: pam_systemd(login:session): Failed to create session: Seat has no VTs but VT number not 0
```
Note that error for creating a session -  I don't know what that means. Do you have an idea?

Thanks in advance!

**Comment by graysky2** [comment]
If something in your OS is expecting tty1 than changing to another like `tty2` should resolve that.  Normally, I have this setup to be your display manger which typically expects to be on `tty1`, at least that is the case on Arch Linux.

Your workaround seems sane to me given your complex use case :smile:   Just be sure you are doing it via a systemd dropin, not be editing the service directly: https://wiki.archlinux.org/title/Systemd#Drop-in_files

For you:
```
## Editing /etc/systemd/system/kodi-gbm.service.d/override.conf
### Anything between here and the comment below will become the contents of the drop-in file

[Service]
TTYPath=
TTYPath=/dev/tty2

### Edits below this comment will be discarded
...
```

I do not know why pam_systemd is angry for you.
> Dec 30 22:09:10 media-player systemd[137]: pam_systemd(login:session): Failed to create session: Seat has no VTs but VT number not 0

Do you see any limited effects while in the kodi-gui?

**Comment by elagil** [comment]
Thanks! I will use a drop-in file then.

No, I have no issues when using kodi, even with that systemd error.

**Comment by elagil** [comment]
I found a solution of someone else regarding my systemd issue (see https://forum.proxmox.com/threads/priviligierte-container-pam_systemd-login-session-failed-to-create-session.119643/). Simply run


```
# systemctl mask systemd-logind
# pam-auth-update
```

and uncheck

```
[  ] Register user sessions in the systemd control group hierarchy
```

in the prompt that opens.

**Comment by Mannshoch** [comment]
@elagil how do you setup proxmox in a way it boots up and switch to kodi?
I assume I have to somehow mount the kodi tty2 to the proxmox tty2 and also modify proxmox to not load tty1 on startup.

Sadly, I did not found any clue how to do that.

**Comment by elagil** [comment]
@Mannshoch  Not sure I understand the question. Can you explain? Do you have trouble with display output?

**Comment by Mannshoch** [comment]
Yes, the display output is the problem.

**Comment by elagil** [comment]
I don't think that this tty issue is at all related.
I passed through my GPU (Intel iGPU) to the container. Otherwise, there is no way for it to have physical graphics output.
