### ISSUE TITLE
After Kodi upgrade to 21.0, there is no HDMI sound

### ISSUE THREAD

**Issue by JuliusLongmind** [graysky2/kodi-standalone-service#48]
Hi there!

Is there any trick to get pipewire to use hdmi output?

Thanks!

**Comment by graysky2** [comment]
I don’t use pipewire. Did the identical setup work under 20.5? If so, that suggests a config issue. Have you looked in the audio section of the Kodi GUI?

**Comment by JuliusLongmind** [comment]
Hey [graysky2](https://github.com/graysky2)!

What I had to do is the following:

1. Enable login for kodi user
2. Change the default sink to the HDMI one: wpctl set-default ID
3. wpctl set-volume @DEFAULT_AUDIO_SINK@ 1.0
4. Disable login and delete password for kodi user

**Comment by graysky2** [comment]
Again, I don't use pipewire and am assuming that `wpctl` is a control tool for it.  If that is true, I am wondering where the output of that command is stored (assuming it is modifying a config file perhaps in `/var/lib/kodi/.config/somewhere` ... is that true?  What I'm getting at is that if the contents of that file are straight forward, a script could create it or you could create it as root and change ownership to kodi:kodi.

**Comment by nebulosa2007** [comment]
I think this can be related: https://github.com/xbmc/xbmc/issues/25006

**Comment by graysky2** [comment]
Thanks for pointing that out.  Glad the issue is upstream and fixed.
