### ISSUE TITLE
README for other distros is misleading

### ISSUE THREAD

**Issue by sjuk** [graysky2/kodi-standalone-service#6]
**Thanks for the great systemd script and the README.** There is only few information about that really elegant way to use kodi without a fiddling with sessions and graphical login managers.

But the following commands use a misleading path. The kodi user needs write access to it's home directory and not only to the .kodi folder. The .kodi folder will be automatically generated by the kodi executable, when it does not already exist.

**Misleading:**
```
mkdir /var/lib/kodi/**.kodi**
chown -R kodi:kodi /var/lib/kodi/**.kodi**
```
**Better could be:**
```
mkdir /var/lib/kodi
chown -R kodi:kodi /var/lib/kodi
```

When adding the user it is assigned to group kodi, but the group was not added. There are some groups that are not available on every distro. I would recommend to add the important ones. The comment 'kodi user' is not that useful, because the username speaks for itself. ;-)

**Misleading:**
```
useradd -c 'kodi user' -u 420 -g kodi -G audio,video,network,optical \
-d /var/lib/kodi -s /usr/bin/nologin kodi
```

**Better could be:**
```
groupadd kodi
useradd -u 420 -g kodi -G audio,video -d /var/lib/kodi -s /usr/bin/nologin kodi
```

I hope I could help in some way by sharing my experiences with your guide.
Have fun
Best regards

**Comment by graysky2** [comment]
Thanks for the feedback.  You're absolutely right about homedir target.  Fixed in https://github.com/graysky2/kodi-standalone-service/commit/d0a037ede7a1577fe37390c99809fc3699d3c483

What I am less clear about is the 2nd suggestion around groups.  I don't have experience on distros outside of Arch with this specifically, but I understand the kodi user to require group membership in audio, video, network, and optical.  I can't find the docs on it to confirm.  Can you point me to a reference where that is spelled out?  Thanks.

**Comment by sjuk** [comment]
Awesome. Thanks for the quick respond. I'm not sure what you need. But I will try to give more details.
When performing your code in a freshly installed Ubuntu 18.04 Server it will lead to the following bash session.
```
$ sudo useradd -u 420 -g kodi -G audio,video,network,optical -d /var/lib/kodi -s /usr/bin/nologin kodi
useradd: group 'kodi' does not exist

$ sudo useradd -u 420 -U -G audio,video,network,optical -d /var/lib/kodi -s /usr/bin/nologin kodi
useradd: group 'network' does not exist
useradd: group 'optical' does not exist

$ sudo useradd -u 420 -U -G audio,video -d /var/lib/kodi -s /usr/bin/nologin kodi
```
In the end only the last command is successful. The -U switch automatically generates a group with the same name as the user to be added. And the groups network and optical simply do not exist in Ubuntu.
When you need more details on command useradd you can use the manual page.

```
$ man useradd

```
Here for example the information about the -U switch.
```
-U, --user-group
    erstellt eine Gruppe mit dem gleichen Name wie der Benutzer und fügt diesen der Gruppe
    hinzu.

    Wenn die Optionen -g, -N und -U nicht angegeben werden, wird das Verhalten durch die
    Variable USERGROUPS_ENAB in /etc/login.defs bestimmt.
```
When you only want one line I would **recommend** to use this command.
```
useradd -u 420 -U -G audio,video -d /var/lib/kodi -s /usr/bin/nologin kodi
```

**Comment by graysky2** [comment]
Tested in a vbox and you're right, thank you for the helpful suggestion.
