### ISSUE TITLE
kodi user does not have correct group memberships for latest libCEC

### ISSUE THREAD

**Issue by dmfay** [graysky2/kodi-standalone-service#9]
hi! I'm using the `kodi-standalone-service` package from the Arch AUR. I upgraded everything a little while ago and found the system could no longer connect to my Pulse-Eight CEC remote control adapter. This turns out to be a [permissions issue](https://github.com/xbmc/xbmc/issues/16053): `/dev/ttyACM0` is (now) owned by the `uucp` group, of which `kodi` is not a member. Adding the group membership manually fixed it for me.

**Comment by graysky2** [comment]
Also, https://aur.archlinux.org/cgit/aur.git/commit/?h=kodi-standalone-service&id=09598c7a5b3e8fa356a7df183172161df37af87a

Thank you for reporting.
